DROP TABLE IF EXISTS ABONNE ;
CREATE TABLE ABONNE (ID_ABONNE INT AUTO_INCREMENT NOT NULL,
PRENOM_ABONNE VARCHAR(200),
NOM_ABONNE VARCHAR(200),
PSEUDO_ABONNE VARCHAR(200),
EMAIL_ABONNE VARCHAR(400),
MDP_ABONNE VARCHAR(16),
REDUCTION_ABONNE TINYINT(1),
DESCRIPTION_ABONNE VARCHAR(2000),
AVATAR_ABONNE VARCHAR(1000),
NIVEAU_ABONNE ENUM,
PRIMARY KEY (ID_ABONNE)) ENGINE=InnoDB;

DROP TABLE IF EXISTS CLUB ;
CREATE TABLE CLUB (ID_CLUB INT AUTO_INCREMENT NOT NULL,
NOM_CLUB VARCHAR(200),
HORAIRES_CLUB VARCHAR(1000),
TEL_CLUB VARCHAR(10),
EMAIL_CLUB VARCHAR(400),
ADRESSE_CLUB VARCHAR(2000),
PRIMARY KEY (ID_CLUB)) ENGINE=InnoDB;

DROP TABLE IF EXISTS TERRAIN ;
CREATE TABLE TERRAIN (ID_TERRAIN INT AUTO_INCREMENT NOT NULL,
COUVERT_TERRAIN TINYINT(1),
TYPE_TERRAIN ENUM,
PRIMARY KEY (ID_TERRAIN)) ENGINE=InnoDB;

DROP TABLE IF EXISTS ENTRAINEUR ;
CREATE TABLE ENTRAINEUR (ID_ENTRAINEUR INT AUTO_INCREMENT NOT NULL,
PRENOM_ENTRAINEUR VARCHAR(200),
NOM_ENTRAINEUR VARCHAR(200),
DESCRIPTION_ENTRAINEUR VARCHAR(2000),
AVATAR_ENTRAINEUR VARCHAR(1000),
PRIMARY KEY (ID_ENTRAINEUR)) ENGINE=InnoDB;

DROP TABLE IF EXISTS ENTRAINEMENT ;
CREATE TABLE ENTRAINEMENT (ID_ENTRAINEMENT INT AUTO_INCREMENT NOT NULL,
HEURE_DEBUT_ENTRAINEMENT DATE,
HEURE_FIN_ENTRAINEMENT DATE,
NIVEAU_ENTRAINEMENT ENUM,
PRIMARY KEY (ID_ENTRAINEMENT)) ENGINE=InnoDB;

DROP TABLE IF EXISTS MATCH ;
CREATE TABLE MATCH (ID_MATCH INT AUTO_INCREMENT NOT NULL,
HEURE_DEBUT_MATCH DATE,
HEURE_FIN_MATCH DATE,
COMPETITION_MATCH TINYINT(1),
PRIMARY KEY (ID_MATCH)) ENGINE=InnoDB;

DROP TABLE IF EXISTS MATCH_ORGANISE ;
CREATE TABLE MATCH_ORGANISE (ID_ABONNE **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_TERRAIN **NOT FOUND** NOT NULL,
ID_MATCH **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_ABONNE,
 ID_TERRAIN,
 ID_MATCH)) ENGINE=InnoDB;

DROP TABLE IF EXISTS ENTRAINE ;
CREATE TABLE ENTRAINE (ID_ENTRAINEMENT **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_ENTRAINEUR **NOT FOUND** NOT NULL,
ID_TERRAIN **NOT FOUND** NOT NULL,
ID_ABONNE **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_ENTRAINEMENT,
 ID_ENTRAINEUR,
 ID_TERRAIN,
 ID_ABONNE)) ENGINE=InnoDB;

DROP TABLE IF EXISTS GAGNE ;
CREATE TABLE GAGNE (ID_ABONNE **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_MATCH **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_ABONNE,
 ID_MATCH)) ENGINE=InnoDB;

DROP TABLE IF EXISTS PERD ;
CREATE TABLE PERD (ID_ABONNE **NOT FOUND** AUTO_INCREMENT NOT NULL,
ID_MATCH **NOT FOUND** NOT NULL,
PRIMARY KEY (ID_ABONNE,
 ID_MATCH)) ENGINE=InnoDB;

ALTER TABLE ABONNE ADD CONSTRAINT FK_ABONNE_ID_CLUB FOREIGN KEY (ID_CLUB) REFERENCES CLUB (ID_CLUB);

ALTER TABLE TERRAIN ADD CONSTRAINT FK_TERRAIN_ID_CLUB FOREIGN KEY (ID_CLUB) REFERENCES CLUB (ID_CLUB);
ALTER TABLE MATCH_ORGANISE ADD CONSTRAINT FK_MATCH_ORGANISE_ID_ABONNE FOREIGN KEY (ID_ABONNE) REFERENCES ABONNE (ID_ABONNE);
ALTER TABLE MATCH_ORGANISE ADD CONSTRAINT FK_MATCH_ORGANISE_ID_TERRAIN FOREIGN KEY (ID_TERRAIN) REFERENCES TERRAIN (ID_TERRAIN);
ALTER TABLE MATCH_ORGANISE ADD CONSTRAINT FK_MATCH_ORGANISE_ID_MATCH FOREIGN KEY (ID_MATCH) REFERENCES MATCH (ID_MATCH);
ALTER TABLE ENTRAINE ADD CONSTRAINT FK_ENTRAINE_ID_ENTRAINEMENT FOREIGN KEY (ID_ENTRAINEMENT) REFERENCES ENTRAINEMENT (ID_ENTRAINEMENT);
ALTER TABLE ENTRAINE ADD CONSTRAINT FK_ENTRAINE_ID_ENTRAINEUR FOREIGN KEY (ID_ENTRAINEUR) REFERENCES ENTRAINEUR (ID_ENTRAINEUR);
ALTER TABLE ENTRAINE ADD CONSTRAINT FK_ENTRAINE_ID_TERRAIN FOREIGN KEY (ID_TERRAIN) REFERENCES TERRAIN (ID_TERRAIN);
ALTER TABLE ENTRAINE ADD CONSTRAINT FK_ENTRAINE_ID_ABONNE FOREIGN KEY (ID_ABONNE) REFERENCES ABONNE (ID_ABONNE);
ALTER TABLE GAGNE ADD CONSTRAINT FK_GAGNE_ID_ABONNE FOREIGN KEY (ID_ABONNE) REFERENCES ABONNE (ID_ABONNE);
ALTER TABLE GAGNE ADD CONSTRAINT FK_GAGNE_ID_MATCH FOREIGN KEY (ID_MATCH) REFERENCES MATCH (ID_MATCH);
ALTER TABLE PERD ADD CONSTRAINT FK_PERD_ID_ABONNE FOREIGN KEY (ID_ABONNE) REFERENCES ABONNE (ID_ABONNE);
ALTER TABLE PERD ADD CONSTRAINT FK_PERD_ID_MATCH FOREIGN KEY (ID_MATCH) REFERENCES MATCH (ID_MATCH);
